### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by DDM203** [biobee/standardanalysis#1]
Hi Derek,
I am sort of playing with the "issues". I put my question on the installation here:

I ran "> devtools::install_github("plasde/standardanalysis", build_vignettes = TRUE)"

But I got error messages:
E  creating vignettes (7.1s)
   --- re-building ‘standard-analysis-tutorial.Rmd’ using rmarkdown
  
   Quitting from lines 108-124 [unnamed-chunk-11] (standard-analysis-tutorial.Rmd)
   Error: processing vignette 'standard-analysis-tutorial.Rmd' failed with diagnostics:
   cannot use 'paired' in formula method
   --- failed re-building ‘standard-analysis-tutorial.Rmd’
  
   SUMMARY: processing the following file failed:
     ‘standard-analysis-tutorial.Rmd’
  
   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'standardanalysis' from GitHub:
  ! System command 'R' failed

Could you help me out? Thanks!
Dongmei

**Comment by plasde** [comment]
Hi Dongmei,

Once the vignette is build the first time with the installation, it should be used as an example of the analysis. The idea is not that you change the vignette yourself and then rebuild.

What you could do is copy the code chunks from the vignette, into your own new .rmd file. This way you can easily save your work on your pc, without rebuilding, as the vignette is something that I provide as a guide. 

With that being said, I do see where it went wrong and I think I spot a mistake on my end. If you type in the bottom left window (terminal) "?multiple_test_alpha()" you can see all the options for the function and how to use them.

The mistake there is that in the example I wrote "pair_by" but in the code it should be "paired = [your variable here]". I will fix this soon but for now I hope this will help.

So, to be clear, if you want to do a paired test, you have to add another argument called "paired" after the argument "method". Don't forget the comma between them and add the variable after paired like so: paired = "my_variable".

Could you let me know if it works or not?
Derek

**Comment by DDM203** [comment]
Hi Derek,
I installed R4.2.3. But I have a problem when installing devtools. After the installation, I see the following errors when loading the library.

> library('devtools')
Loading required package: usethis
Error: package or namespace load failed for ‘devtools’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘shiny’

**Comment by DDM203** [comment]
ok, the issue is related to R version. For Mac, it needs R 4.3.3, not 4.4.0 or 4.2.3. In Windows 11, I used R4.3.2. It is also fine with building vignettes. But I got error messages that a few packages cannot be installed because the path is not writtable. i am not able to change the properties of the path yet.
