### ISSUE TITLE
Problem with Input data

### ISSUE THREAD

**Issue by DDM203** [biobee/standardanalysis#2]
Hi Derek,
I could install everything. I follow the instruction, but am stuck here "ps <- import_data(biom_file_name, mapping_file_name)". It shows: 
Error in import_data(biom_file_name, mapping_file_name) : 
  could not find function "import_data"

I load vignette('standard-analysis-tutorial', package = 'standardanalysis'). It did not give any error. I also define input_directory, biofilm_file_name, mapping_file_name (using the test files). 

What can be the problem?

**Comment by plasde** [comment]
Hi,
Did you begin the analysis with `library("standardanalysis")` to also load the package?
